### ISSUE TITLE
Haul bundler stuck

### ISSUE THREAD

**Issue by Woren** [ScottPierce/kotlin-react-native#2]
Bundling app takes 15+ minutes. Sometimes it looks like it gets stuck. When trying to use metro bundler it also gets stuck. It looks like there is problem with kotlin imports in App.js when I use for example:
`import * as shared from './shared/build/classes/kotlin/main/shared.js'`
When this line is not there everything works smoothly. Is this something you are aware of? Maybe this is problem with Hault / Metro itself? Or do you have any it how make it faster? Thank you

**Comment by ScottPierce** [comment]
I mention this in the readme, but it sounds like you are dealing with: https://github.com/facebook/metro/issues/123

**Comment by Woren** [comment]
Yes, you're right. I figured it out. For anybody else using Metro or Hault - these lines in .babelrc should help.
```
{
  "presets": ["react-native"],
  "ignore": [
    "**/shared.js"
  ]
}
```
